/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/room-optimized.glb -o src/components/projects/3dfiles/Room.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type ActionName = string
type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
    Plane_4: THREE.Mesh
    Plane_5: THREE.Mesh
    Plane_6: THREE.Mesh
    Plane_7: THREE.Mesh
    Plane_8: THREE.Mesh
    Plane_9: THREE.Mesh
    Plane_10: THREE.Mesh
    Plane_11: THREE.Mesh
    Plane_12: THREE.Mesh
    Plane_13: THREE.Mesh
    Plane_14: THREE.Mesh
    Plane_15: THREE.Mesh
    Plane_16: THREE.Mesh
    Plane_17: THREE.Mesh
    Plane_18: THREE.Mesh
    Plane_19: THREE.Mesh
    Plane_20: THREE.Mesh
    Plane_21: THREE.Mesh
    Plane_22: THREE.Mesh
    Plane_23: THREE.Mesh
    Plane_24: THREE.Mesh
    Plane_25: THREE.Mesh
    Plane_26: THREE.Mesh
    Plane_27: THREE.Mesh
    Plane_28: THREE.Mesh
    Plane_29: THREE.Mesh
    Plane_30: THREE.Mesh
    Plane_31: THREE.Mesh
    Plane_32: THREE.Mesh
    Plane_33: THREE.Mesh
    Plane_34: THREE.Mesh
    Plane_35: THREE.Mesh
    Plane_36: THREE.Mesh
    Plane_37: THREE.Mesh
    Plane_38: THREE.Mesh
    Plane_39: THREE.Mesh
    Plane_40: THREE.Mesh
    Plane_41: THREE.Mesh
    Plane_42: THREE.Mesh
    Plane_43: THREE.Mesh
    Plane_44: THREE.Mesh
    Plane_45: THREE.Mesh
    Plane_46: THREE.Mesh
    Plane_47: THREE.Mesh
    Plane_48: THREE.Mesh
    Plane_49: THREE.Mesh
    Plane_50: THREE.Mesh
    Plane_51: THREE.Mesh
    Keyboard_Light001: THREE.Mesh
  }
  materials: {
    ['Light Floor Tiling']: THREE.MeshStandardMaterial
    ['Wood.120']: THREE.MeshStandardMaterial
    ['Brown Polished Oak Wood']: THREE.MeshStandardMaterial
    ['Wood.002']: THREE.MeshStandardMaterial
    ['Old Book: David Balfour']: THREE.MeshStandardMaterial
    alice: THREE.MeshStandardMaterial
    paper: THREE.MeshStandardMaterial
    ['design book.001']: THREE.MeshPhysicalMaterial
    ['Vintage Office Cash Records Book']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Mat.']: THREE.MeshStandardMaterial
    ['OLD BOOK: The Secret Warning']: THREE.MeshStandardMaterial
    ['Old Book: Tennyson - Arlington Edition']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    Manual: THREE.MeshStandardMaterial
    ['Books.04']: THREE.MeshStandardMaterial
    ['Wood.001']: THREE.MeshStandardMaterial
    ['Headphone Bluedeep']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    ['Screen Image']: THREE.MeshStandardMaterial
    ['00-Fabric matress']: THREE.MeshStandardMaterial
    ['00-Fabric Matress UP']: THREE.MeshStandardMaterial
    fabric: THREE.MeshStandardMaterial
    ['pillow brown']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['Cover book-03.001']: THREE.MeshStandardMaterial
    ['paper.002']: THREE.MeshStandardMaterial
    ['Cover book-02.001']: THREE.MeshStandardMaterial
    ['Cover book-01.001']: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshPhysicalMaterial
    PaletteMaterial007: THREE.MeshPhysicalMaterial
    potted_plant_04: THREE.MeshStandardMaterial
    ['Laptop Keyboard']: THREE.MeshStandardMaterial
    ['Glossy Black Metal – PBR Material']: THREE.MeshStandardMaterial
    ['Tv Screen']: THREE.MeshStandardMaterial
    ['Swirled Light Wood Grain']: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    ['Rough Pitted Wood']: THREE.MeshStandardMaterial
    ['Laptop Screen']: THREE.MeshStandardMaterial
    ['Wood.003']: THREE.MeshStandardMaterial
    ['Marble 5']: THREE.MeshStandardMaterial
    ['Plaster Wall Material']: THREE.MeshStandardMaterial
    ['Wall bricks']: THREE.MeshStandardMaterial
    ['Plaster wall']: THREE.MeshStandardMaterial
    PTRC0UCMAEN5DP4M_MAT_MR: THREE.MeshStandardMaterial
    ['blue keys']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.ComponentProps<'group'>) {
const { nodes, materials } = useGLTF('/models/room-optimized.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Keyboard_Light001.geometry} material={materials.PaletteMaterial008} position={[4.49, 0.543, -3.906]} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Light Floor Tiling']} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['Wood.120']} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials['Brown Polished Oak Wood']} />
      <mesh geometry={nodes.Plane_4.geometry} material={materials['Wood.002']} />
      <mesh geometry={nodes.Plane_5.geometry} material={materials['Old Book: David Balfour']} />
      <mesh geometry={nodes.Plane_6.geometry} material={materials.alice} />
      <mesh geometry={nodes.Plane_7.geometry} material={materials.paper} />
      <mesh geometry={nodes.Plane_8.geometry} material={materials['design book.001']} />
      <mesh geometry={nodes.Plane_9.geometry} material={materials['Vintage Office Cash Records Book']} />
      <mesh geometry={nodes.Plane_10.geometry} material={materials.Material} />
      <mesh geometry={nodes.Plane_11.geometry} material={materials['Mat.']} />
      <mesh geometry={nodes.Plane_12.geometry} material={materials['OLD BOOK: The Secret Warning']} />
      <mesh geometry={nodes.Plane_13.geometry} material={materials['Old Book: Tennyson - Arlington Edition']} />
      <mesh geometry={nodes.Plane_14.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Plane_15.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Plane_16.geometry} material={materials.Manual} />
      <mesh geometry={nodes.Plane_17.geometry} material={materials['Books.04']} />
      <mesh geometry={nodes.Plane_18.geometry} material={materials['Wood.001']} />
      <mesh geometry={nodes.Plane_19.geometry} material={materials['Headphone Bluedeep']} />
      <mesh geometry={nodes.Plane_20.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Plane_21.geometry} material={materials['Screen Image']} />
      <mesh geometry={nodes.Plane_22.geometry} material={materials['00-Fabric matress']} />
      <mesh geometry={nodes.Plane_23.geometry} material={materials['00-Fabric Matress UP']} />
      <mesh geometry={nodes.Plane_24.geometry} material={materials.fabric} />
      <mesh geometry={nodes.Plane_25.geometry} material={materials['pillow brown']} />
      <mesh geometry={nodes.Plane_26.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Plane_27.geometry} material={materials['Cover book-03.001']} />
      <mesh geometry={nodes.Plane_28.geometry} material={materials['paper.002']} />
      <mesh geometry={nodes.Plane_29.geometry} material={materials['Cover book-02.001']} />
      <mesh geometry={nodes.Plane_30.geometry} material={materials['Cover book-01.001']} />
      <mesh geometry={nodes.Plane_31.geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes.Plane_32.geometry} material={materials.PaletteMaterial006} />
      <mesh geometry={nodes.Plane_33.geometry} material={materials.PaletteMaterial007} />
      <mesh geometry={nodes.Plane_34.geometry} material={materials.potted_plant_04} />
      <mesh geometry={nodes.Plane_35.geometry} material={materials['Laptop Keyboard']} />
      <mesh geometry={nodes.Plane_36.geometry} material={materials['Glossy Black Metal – PBR Material']} />
      <mesh geometry={nodes.Plane_37.geometry} material={materials['Tv Screen']} />
      <mesh geometry={nodes.Plane_38.geometry} material={materials['Swirled Light Wood Grain']} />
      <mesh geometry={nodes.Plane_39.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane_40.geometry} material={materials['Rough Pitted Wood']} />
      <mesh geometry={nodes.Plane_41.geometry} material={materials['Laptop Screen']} />
      <mesh geometry={nodes.Plane_42.geometry} material={nodes.Plane_42.material} />
      <mesh geometry={nodes.Plane_43.geometry} material={materials['Wood.003']} />
      <mesh geometry={nodes.Plane_44.geometry} material={materials['Marble 5']} />
      <mesh geometry={nodes.Plane_45.geometry} material={materials['Plaster Wall Material']} />
      <mesh geometry={nodes.Plane_46.geometry} material={materials['Wall bricks']} />
      <mesh geometry={nodes.Plane_47.geometry} material={materials['Plaster wall']} />
      <mesh geometry={nodes.Plane_48.geometry} material={materials.PTRC0UCMAEN5DP4M_MAT_MR} />
      <mesh geometry={nodes.Plane_49.geometry} material={materials['blue keys']} />
      <mesh geometry={nodes.Plane_50.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Plane_51.geometry} material={materials.PaletteMaterial005} />
    </group>
  )
}

useGLTF.preload('/models/room-optimized.glb')
